// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CloseSABS</b><br>
 * Generated     : <b>2012/09/18 14:51:52</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  ÒÂÌÚˇ·ˇ 18, 2012
 * @author Admin
 */
public abstract class CloseSABSHelper extends RationalTestScript
{
	/**
	 * ƒ‡: with default state.
	 *		.text : ƒ‡
	 * 		.class : .Pushbutton
	 * 		.name : ƒ‡
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Closebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Closebutton"));
	}
	/**
	 * ƒ‡: with specific test context and state.
	 *		.text : ƒ‡
	 * 		.class : .Pushbutton
	 * 		.name : ƒ‡
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Closebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Closebutton"), anchor, flags);
	}
	
	/**
	 * _044582002œ”¡¿Õ ¿–Œ——»»«¿œ¿ƒÕŒ≈: with default state.
	 *		.text : 044582002 œ” ¡¿Õ ¿ –Œ——»» «¿œ¿ƒÕŒ≈
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 œ” ¡¿Õ ¿ –Œ——»» «¿œ¿ƒÕŒ≈
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002œ”¡¿Õ ¿–Œ——»»«¿œ¿ƒÕŒ≈: with specific test context and state.
	 *		.text : 044582002 œ” ¡¿Õ ¿ –Œ——»» «¿œ¿ƒÕŒ≈
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 œ” ¡¿Õ ¿ –Œ——»» «¿œ¿ƒÕŒ≈
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	/**
	 * Œ : with default state.
	 *		.text : Œ 
	 * 		.class : .Pushbutton
	 * 		.name : Œ 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SKADerbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("SKADerbutton"));
	}
	/**
	 * Œ : with specific test context and state.
	 *		.text : Œ 
	 * 		.class : .Pushbutton
	 * 		.name : Œ 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SKADerbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("SKADerbutton"), anchor, flags);
	}
	
	

	protected CloseSABSHelper()
	{
		setScriptName("SABS.CloseSABS");
	}
	
}

