// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CreateSignedXML</b><br>
 * Generated     : <b>2013/04/04 15:48:29</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  апреля 04, 2013
 * @author Admin
 */
public abstract class CreateSignedXMLHelper extends RationalTestScript
{
	/**
	 * ЗагрузкаКлючаСНосителя: with default state.
	 *		.text : Загрузка ключа с носителя
	 * 		.class : #32770
	 * 		.processName : ConvXML.exe
	 * 		.name : Загрузка ключа с носителя
	 */
	protected TopLevelSubitemTestObject loadKeywindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("loadKeywindow"));
	}
	/**
	 * ЗагрузкаКлючаСНосителя: with specific test context and state.
	 *		.text : Загрузка ключа с носителя
	 * 		.class : #32770
	 * 		.processName : ConvXML.exe
	 * 		.name : Загрузка ключа с носителя
	 */
	protected TopLevelSubitemTestObject loadKeywindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("loadKeywindow"), anchor, flags);
	}
	
	/**
	 * Далее: with default state.
	 *		.text : Далее >
	 * 		.class : .Pushbutton
	 * 		.name : Далее >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject nextbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("nextbutton"));
	}
	/**
	 * Далее: with specific test context and state.
	 *		.text : Далее >
	 * 		.class : .Pushbutton
	 * 		.name : Далее >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject nextbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("nextbutton"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"), anchor, flags);
	}
	
	/**
	 * Готово: with default state.
	 *		.text : Готово
	 * 		.class : .Pushbutton
	 * 		.name : Готово
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readybutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("readybutton"));
	}
	/**
	 * Готово: with specific test context and state.
	 *		.text : Готово
	 * 		.class : .Pushbutton
	 * 		.name : Готово
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readybutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("readybutton"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject selectProfilecomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("selectProfilecomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject selectProfilecomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("selectProfilecomboBox"), anchor, flags);
	}
	
	

	protected CreateSignedXMLHelper()
	{
		setScriptName("SABS.CreateSignedXML");
	}
	
}

