// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>InitSign</b><br>
 * Generated     : <b>2013/04/01 16:07:34</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  апреля 01, 2013
 * @author Admin
 */
public abstract class InitSignHelper extends RationalTestScript
{
	/**
	 * ComboBox: with default state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"), anchor, flags);
	}
	
	/**
	 * List1: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list1table() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list1table"));
	}
	/**
	 * List1: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list1table(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list1table"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton2"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton2"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton3"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton3"), anchor, flags);
	}
	
	/**
	 * БиологическийДСЧ: with default state.
	 *		.text : Биологический ДСЧ
	 * 		.class : #32770
	 * 		.processName : scs.exe
	 * 		.name : Биологический ДСЧ
	 */
	protected TopLevelSubitemTestObject биологическийДСЧwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("биологическийДСЧwindow"));
	}
	/**
	 * БиологическийДСЧ: with specific test context and state.
	 *		.text : Биологический ДСЧ
	 * 		.class : #32770
	 * 		.processName : scs.exe
	 * 		.name : Биологический ДСЧ
	 */
	protected TopLevelSubitemTestObject биологическийДСЧwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("биологическийДСЧwindow"), anchor, flags);
	}
	
	/**
	 * Да: with default state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject даbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("даbutton"));
	}
	/**
	 * Да: with specific test context and state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject даbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("даbutton"), anchor, flags);
	}
	
	/**
	 * СправочникСертификатов: with default state.
	 *		.text : Справочник сертификатов
	 * 		.class : Afx:1000000:b:10013:6:c01f5
	 * 		.processName : scs.exe
	 * 		.name : Справочник сертификатов
	 */
	protected TopLevelSubitemTestObject справочникСертификатовwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("справочникСертификатовwindow"));
	}
	/**
	 * СправочникСертификатов: with specific test context and state.
	 *		.text : Справочник сертификатов
	 * 		.class : Afx:1000000:b:10013:6:c01f5
	 * 		.processName : scs.exe
	 * 		.name : Справочник сертификатов
	 */
	protected TopLevelSubitemTestObject справочникСертификатовwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("справочникСертификатовwindow"), anchor, flags);
	}
	
	/**
	 * УкажитеКлючДляИнициализацииДСЧ: with default state.
	 *		.text : Укажите ключ для инициализации ДСЧ
	 * 		.class : #32770
	 * 		.processName : scs.exe
	 * 		.name : Укажите ключ для инициализации ДСЧ
	 */
	protected TopLevelSubitemTestObject укажитеКлючДляИнициализацииДСЧ() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("укажитеКлючДляИнициализацииДСЧ"));
	}
	/**
	 * УкажитеКлючДляИнициализацииДСЧ: with specific test context and state.
	 *		.text : Укажите ключ для инициализации ДСЧ
	 * 		.class : #32770
	 * 		.processName : scs.exe
	 * 		.name : Укажите ключ для инициализации ДСЧ
	 */
	protected TopLevelSubitemTestObject укажитеКлючДляИнициализацииДСЧ(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("укажитеКлючДляИнициализацииДСЧ"), anchor, flags);
	}
	
	

	protected InitSignHelper()
	{
		setScriptName("SABS.InitSign");
	}
	
}

