// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Reset</b><br>
 * Generated     : <b>2012/10/23 13:44:55</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  октября 23, 2012
 * @author Admin
 */
public abstract class ResetHelper extends RationalTestScript
{
	/**
	 * Да: with default state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Confirmbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Confirmbutton"));
	}
	/**
	 * Да: with specific test context and state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Confirmbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Confirmbutton"), anchor, flags);
	}
	
	/**
	 * ПараметрыПодключенияКБД: with default state.
	 *		.text : Параметры подключения к БД
	 * 		.class : TfmSaLoginParam
	 * 		.processName : sabs_set.exe
	 * 		.name : Параметры подключения к БД
	 */
	protected TopLevelSubitemTestObject DBpasswindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("DBpasswindow"));
	}
	/**
	 * ПараметрыПодключенияКБД: with specific test context and state.
	 *		.text : Параметры подключения к БД
	 * 		.class : TfmSaLoginParam
	 * 		.processName : sabs_set.exe
	 * 		.name : Параметры подключения к БД
	 */
	protected TopLevelSubitemTestObject DBpasswindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("DBpasswindow"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Dumptree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Dumptree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Dumptree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Dumptree"), anchor, flags);
	}
	
	/**
	 * Внимание: with default state.
	 *		.text : Внимание
	 * 		.class : #32770
	 * 		.processName : sabs_set.exe
	 * 		.name : Внимание
	 */
	protected TopLevelSubitemTestObject Endwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Endwindow"));
	}
	/**
	 * Внимание: with specific test context and state.
	 *		.text : Внимание
	 * 		.class : #32770
	 * 		.processName : sabs_set.exe
	 * 		.name : Внимание
	 */
	protected TopLevelSubitemTestObject Endwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Endwindow"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject FileOKbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("FileOKbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject FileOKbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("FileOKbutton"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Passokbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Passokbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Passokbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Passokbutton"), anchor, flags);
	}
	
	/**
	 * НастройкаИПусковыеРешенияПКСАБС: with default state.
	 *		.text : Настройка и пусковые решения ПК "САБС"
	 * 		.class : TfmSabsSetup
	 * 		.processName : sabs_set.exe
	 * 		.name : Настройка и пусковые решения ПК "САБС"
	 */
	protected TopLevelSubitemTestObject SABSSetwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSSetwindow"));
	}
	/**
	 * НастройкаИПусковыеРешенияПКСАБС: with specific test context and state.
	 *		.text : Настройка и пусковые решения ПК "САБС"
	 * 		.class : TfmSabsSetup
	 * 		.processName : sabs_set.exe
	 * 		.name : Настройка и пусковые решения ПК "САБС"
	 */
	protected TopLevelSubitemTestObject SABSSetwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSSetwindow"), anchor, flags);
	}
	
	/**
	 * ОК: with default state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject окbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("окbutton"));
	}
	/**
	 * ОК: with specific test context and state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject окbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("окbutton"), anchor, flags);
	}
	
	

	protected ResetHelper()
	{
		setScriptName("SABS.Reset");
	}
	
}

