// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SignFile</b><br>
 * Generated     : <b>2012/06/18 16:49:32</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  июня 18, 2012
 * @author Admin
 */
public abstract class SignFileHelper extends RationalTestScript
{
	/**
	 * Далее: with default state.
	 *		.text : Далее >
	 * 		.class : .Pushbutton
	 * 		.name : Далее >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Nextbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Nextbutton"));
	}
	/**
	 * Далее: with specific test context and state.
	 *		.text : Далее >
	 * 		.class : .Pushbutton
	 * 		.name : Далее >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Nextbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Nextbutton"), anchor, flags);
	}
	
	/**
	 * Готово: with default state.
	 *		.text : Готово
	 * 		.class : .Pushbutton
	 * 		.name : Готово
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Readybutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Readybutton"));
	}
	/**
	 * Готово: with specific test context and state.
	 *		.text : Готово
	 * 		.class : .Pushbutton
	 * 		.name : Готово
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Readybutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Readybutton"), anchor, flags);
	}
	
	

	protected SignFileHelper()
	{
		setScriptName("SABS.SignFile");
	}
	
}

