// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>StartSABS</b><br>
 * Generated     : <b>2012/10/22 9:07:11</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  îêòÿáðÿ 22, 2012
 * @author Admin
 */
public abstract class StartSABSHelper extends RationalTestScript
{
	/**
	 * ÇàãðóçêàÊëþ÷àÑÍîñèòåëÿ: with default state.
	 *		.text : Çàãðóçêà êëþ÷à ñ íîñèòåëÿ
	 * 		.class : #32770
	 * 		.processName : ConvXml.exe
	 * 		.name : Çàãðóçêà êëþ÷à ñ íîñèòåëÿ
	 */
	protected TopLevelSubitemTestObject LoadSignwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("LoadSignwindow"));
	}
	/**
	 * ÇàãðóçêàÊëþ÷àÑÍîñèòåëÿ: with specific test context and state.
	 *		.text : Çàãðóçêà êëþ÷à ñ íîñèòåëÿ
	 * 		.class : #32770
	 * 		.processName : ConvXml.exe
	 * 		.name : Çàãðóçêà êëþ÷à ñ íîñèòåëÿ
	 */
	protected TopLevelSubitemTestObject LoadSignwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("LoadSignwindow"), anchor, flags);
	}
	
	/**
	 * ÄîñòóïÊÑèñòåìå: with default state.
	 *		.text : Äîñòóï ê ñèñòåìå
	 * 		.class : TfmYADMLogin
	 * 		.processName : purs_loader.exe
	 * 		.name : Äîñòóï ê ñèñòåìå
	 */
	protected TopLevelSubitemTestObject Loginwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Loginwindow"));
	}
	/**
	 * ÄîñòóïÊÑèñòåìå: with specific test context and state.
	 *		.text : Äîñòóï ê ñèñòåìå
	 * 		.class : TfmYADMLogin
	 * 		.processName : purs_loader.exe
	 * 		.name : Äîñòóï ê ñèñòåìå
	 */
	protected TopLevelSubitemTestObject Loginwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Loginwindow"), anchor, flags);
	}
	
	/**
	 * _044582002ÏÓÁÀÍÊÀÐÎÑÑÈÈÇÀÏÀÄÍÎÅ: with default state.
	 *		.text : 044582002 ÏÓ ÁÀÍÊÀ ÐÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ÏÓ ÁÀÍÊÀ ÐÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002ÏÓÁÀÍÊÀÐÎÑÑÈÈÇÀÏÀÄÍÎÅ: with specific test context and state.
	 *		.text : 044582002 ÏÓ ÁÀÍÊÀ ÐÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ÏÓ ÁÀÍÊÀ ÐÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	/**
	 * Äà: with default state.
	 *		.text : Äà
	 * 		.class : .Pushbutton
	 * 		.name : Äà
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignComnfirmbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignComnfirmbutton"));
	}
	/**
	 * Äà: with specific test context and state.
	 *		.text : Äà
	 * 		.class : .Pushbutton
	 * 		.name : Äà
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignComnfirmbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignComnfirmbutton"), anchor, flags);
	}
	
	/**
	 * Ãîòîâî: with default state.
	 *		.text : Ãîòîâî
	 * 		.class : .Pushbutton
	 * 		.name : Ãîòîâî
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignDonebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignDonebutton"));
	}
	/**
	 * Ãîòîâî: with specific test context and state.
	 *		.text : Ãîòîâî
	 * 		.class : .Pushbutton
	 * 		.name : Ãîòîâî
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignDonebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignDonebutton"), anchor, flags);
	}
	
	/**
	 * Äàëåå: with default state.
	 *		.text : Äàëåå >
	 * 		.class : .Pushbutton
	 * 		.name : Äàëåå >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignNextbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignNextbutton"));
	}
	/**
	 * Äàëåå: with specific test context and state.
	 *		.text : Äàëåå >
	 * 		.class : .Pushbutton
	 * 		.name : Äàëåå >
	 * 		.classIndex : 0
	 */
	protected GuiTestObject SignNextbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("SignNextbutton"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject SigncomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("SigncomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject SigncomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("SigncomboBox"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Signokbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Signokbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Signokbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Signokbutton"), anchor, flags);
	}
	
	

	protected StartSABSHelper()
	{
		setScriptName("SABS.StartSABS");
	}
	
}

