// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.SABS;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>StartSABS</b><br>
 * Generated     : <b>2013/11/07 10:57:07</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  ноября 07, 2013
 * @author admin
 */
public abstract class StartSABSHelper extends RationalTestScript
{
	/**
	 * ВыберитеПрофиль: with default state.
	 *		.text : Выберите профиль
	 * 		.class : #32770
	 * 		.processName : ConvXml.exe
	 * 		.name : Выберите профиль
	 */
	protected TopLevelSubitemTestObject Profilewindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Profilewindow"));
	}
	/**
	 * ВыберитеПрофиль: with specific test context and state.
	 *		.text : Выберите профиль
	 * 		.class : #32770
	 * 		.processName : ConvXml.exe
	 * 		.name : Выберите профиль
	 */
	protected TopLevelSubitemTestObject Profilewindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Profilewindow"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : null
	 * 		.class : ComboBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"), anchor, flags);
	}
	
	/**
	 * Подтверждение: with default state.
	 *		.text : Подтверждение
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Подтверждение
	 */
	protected TopLevelSubitemTestObject confwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("confwindow"));
	}
	/**
	 * Подтверждение: with specific test context and state.
	 *		.text : Подтверждение
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Подтверждение
	 */
	protected TopLevelSubitemTestObject confwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("confwindow"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton2"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton2"), anchor, flags);
	}
	
	/**
	 * Text: with default state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject texttext() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("texttext"));
	}
	/**
	 * Text: with specific test context and state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject texttext(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("texttext"), anchor, flags);
	}
	
	/**
	 * Да: with default state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject даbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("даbutton"));
	}
	/**
	 * Да: with specific test context and state.
	 *		.text : Да
	 * 		.class : .Pushbutton
	 * 		.name : Да
	 * 		.classIndex : 0
	 */
	protected GuiTestObject даbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("даbutton"), anchor, flags);
	}
	
	/**
	 * ДоступКСистеме: with default state.
	 *		.text : Доступ к системе
	 * 		.class : TfmYADMLogin
	 * 		.processName : purs_loader.exe
	 * 		.name : Доступ к системе
	 */
	protected TopLevelSubitemTestObject доступКСистемеwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("доступКСистемеwindow"));
	}
	/**
	 * ДоступКСистеме: with specific test context and state.
	 *		.text : Доступ к системе
	 * 		.class : TfmYADMLogin
	 * 		.processName : purs_loader.exe
	 * 		.name : Доступ к системе
	 */
	protected TopLevelSubitemTestObject доступКСистемеwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("доступКСистемеwindow"), anchor, flags);
	}
	
	

	protected StartSABSHelper()
	{
		setScriptName("SABS.StartSABS");
	}
	
}

