// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Modules;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>OtvetEO</b><br>
 * Generated     : <b>2013/10/31 12:32:48</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  октября 31, 2013
 * @author admin
 */
public abstract class OtvetEOHelper extends RationalTestScript
{
	/**
	 * УведомлениеОРезультатахПриемаКИсполнениюВыставляемогоНаОплатуИнкассовогоПоручения: with default state.
	 *		.text : Уведомление о результатах приема к исполнению выставляемого на оплату  инкассово ...
	 * 		.class : TfmEpayED274
	 * 		.processName : purs_loader.exe
	 * 		.name : Уведомление о результатах приема к исполнению выставляемого на оплату  инкассово ...
	 */
	protected TopLevelSubitemTestObject ED274window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ED274window"));
	}
	/**
	 * УведомлениеОРезультатахПриемаКИсполнениюВыставляемогоНаОплатуИнкассовогоПоручения: with specific test context and state.
	 *		.text : Уведомление о результатах приема к исполнению выставляемого на оплату  инкассово ...
	 * 		.class : TfmEpayED274
	 * 		.processName : purs_loader.exe
	 * 		.name : Уведомление о результатах приема к исполнению выставляемого на оплату  инкассово ...
	 */
	protected TopLevelSubitemTestObject ED274window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ED274window"), anchor, flags);
	}
	
	/**
	 * ОтключитьПанель: with default state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject ESpanel() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("ESpanel"));
	}
	/**
	 * ОтключитьПанель: with specific test context and state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject ESpanel(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("ESpanel"), anchor, flags);
	}
	
	/**
	 * Ошибка: with default state.
	 *		.text : Ошибка
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Ошибка
	 */
	protected TopLevelSubitemTestObject Errorwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Errorwindow"));
	}
	/**
	 * Ошибка: with specific test context and state.
	 *		.text : Ошибка
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Ошибка
	 */
	protected TopLevelSubitemTestObject Errorwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Errorwindow"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"), anchor, flags);
	}
	
	/**
	 * ОК: with default state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OKerrorbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("OKerrorbutton"));
	}
	/**
	 * ОК: with specific test context and state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OKerrorbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("OKerrorbutton"), anchor, flags);
	}
	
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with default state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with specific test context and state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	

	protected OtvetEOHelper()
	{
		setScriptName("Modules.OtvetEO");
	}
	
}

