// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.PrProvod.PervVvod;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ContrVvod</b><br>
 * Generated     : <b>2012/05/24 14:55:27</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  мая 24, 2012
 * @author Admin
 */
public abstract class ContrVvodHelper extends RationalTestScript
{
	/**
	 * ДокументыКонтрольногоВвода: with default state.
	 *		.text : Документы контрольного ввода
	 * 		.class : TfmDublDoclistMain
	 * 		.processName : purs_loader.exe
	 * 		.name : Документы контрольного ввода
	 */
	protected TopLevelSubitemTestObject ContrDocwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ContrDocwindow"));
	}
	/**
	 * ДокументыКонтрольногоВвода: with specific test context and state.
	 *		.text : Документы контрольного ввода
	 * 		.class : TfmDublDoclistMain
	 * 		.processName : purs_loader.exe
	 * 		.name : Документы контрольного ввода
	 */
	protected TopLevelSubitemTestObject ContrDocwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ContrDocwindow"), anchor, flags);
	}
	
	/**
	 * ОперацияКонтрольТекстовыхРеквизитов: with default state.
	 *		.text : Операция - Контроль текстовых реквизитов 
	 * 		.class : TfmInputform001
	 * 		.processName : purs_loader.exe
	 * 		.name : Операция - Контроль текстовых реквизитов 
	 */
	protected TopLevelSubitemTestObject ControlTextwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ControlTextwindow"));
	}
	/**
	 * ОперацияКонтрольТекстовыхРеквизитов: with specific test context and state.
	 *		.text : Операция - Контроль текстовых реквизитов 
	 * 		.class : TfmInputform001
	 * 		.processName : purs_loader.exe
	 * 		.name : Операция - Контроль текстовых реквизитов 
	 */
	protected TopLevelSubitemTestObject ControlTextwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ControlTextwindow"), anchor, flags);
	}
	
	/**
	 * КонтрольныйВвод: with default state.
	 *		.text : Контрольный ввод 
	 * 		.class : TfmdublcontrolInput001
	 * 		.processName : purs_loader.exe
	 * 		.name : Контрольный ввод 
	 */
	protected TopLevelSubitemTestObject Inputwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Inputwindow"));
	}
	/**
	 * КонтрольныйВвод: with specific test context and state.
	 *		.text : Контрольный ввод 
	 * 		.class : TfmdublcontrolInput001
	 * 		.processName : purs_loader.exe
	 * 		.name : Контрольный ввод 
	 */
	protected TopLevelSubitemTestObject Inputwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Inputwindow"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"), anchor, flags);
	}
	
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with default state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with specific test context and state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	

	protected ContrVvodHelper()
	{
		setScriptName("PrProvod.PervVvod.ContrVvod");
	}
	
}

