// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.PrProvod.PervVvod;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Vvod</b><br>
 * Generated     : <b>2012/12/13 8:57:48</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  декабря 13, 2012
 * @author Admin
 */
public abstract class VvodHelper extends RationalTestScript
{
	/**
	 * ВводИРедактированиеПДРасчетныйДокумент: with default state.
	 *		.text : Ввод и редактирование ПД - Расчетный документ
	 * 		.class : Tfmpudocsinput
	 * 		.processName : purs_loader.exe
	 * 		.name : Ввод и редактирование ПД - Расчетный документ
	 */
	protected TopLevelSubitemTestObject Docswindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Docswindow"));
	}
	/**
	 * ВводИРедактированиеПДРасчетныйДокумент: with specific test context and state.
	 *		.text : Ввод и редактирование ПД - Расчетный документ
	 * 		.class : Tfmpudocsinput
	 * 		.processName : purs_loader.exe
	 * 		.name : Ввод и редактирование ПД - Расчетный документ
	 */
	protected TopLevelSubitemTestObject Docswindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Docswindow"), anchor, flags);
	}
	
	/**
	 * ОК: with default state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ExistDocOkbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ExistDocOkbutton"));
	}
	/**
	 * ОК: with specific test context and state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ExistDocOkbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ExistDocOkbutton"), anchor, flags);
	}
	
	/**
	 * Внимание: with default state.
	 *		.text : Внимание
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Внимание
	 */
	protected TopLevelSubitemTestObject ExistDocwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ExistDocwindow"));
	}
	/**
	 * Внимание: with specific test context and state.
	 *		.text : Внимание
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Внимание
	 */
	protected TopLevelSubitemTestObject ExistDocwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ExistDocwindow"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject FolderOkbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("FolderOkbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject FolderOkbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("FolderOkbutton"), anchor, flags);
	}
	
	/**
	 * ДобавлениеДокументовВПачкуКВ: with default state.
	 *		.text : Добавление документов в пачку КВ
	 * 		.class : TfmDublPackCreate
	 * 		.processName : purs_loader.exe
	 * 		.name : Добавление документов в пачку КВ
	 */
	protected TopLevelSubitemTestObject Folderwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Folderwindow"));
	}
	/**
	 * ДобавлениеДокументовВПачкуКВ: with specific test context and state.
	 *		.text : Добавление документов в пачку КВ
	 * 		.class : TfmDublPackCreate
	 * 		.processName : purs_loader.exe
	 * 		.name : Добавление документов в пачку КВ
	 */
	protected TopLevelSubitemTestObject Folderwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Folderwindow"), anchor, flags);
	}
	
	/**
	 * ОперацияРасчетныйДокумент: with default state.
	 *		.text : Операция - Расчетный документ
	 * 		.class : TfmInputform001
	 * 		.processName : purs_loader.exe
	 * 		.name : Операция - Расчетный документ
	 */
	protected TopLevelSubitemTestObject Inputwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Inputwindow"));
	}
	/**
	 * ОперацияРасчетныйДокумент: with specific test context and state.
	 *		.text : Операция - Расчетный документ
	 * 		.class : TfmInputform001
	 * 		.processName : purs_loader.exe
	 * 		.name : Операция - Расчетный документ
	 */
	protected TopLevelSubitemTestObject Inputwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Inputwindow"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Menutree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menutree"), anchor, flags);
	}
	
	/**
	 * распечататьРеестр: with default state.
	 *		.text : распечатать реестр
	 * 		.class : .Checkbutton
	 * 		.name : распечатать реестр
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject PrintcheckBox() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PrintcheckBox"));
	}
	/**
	 * распечататьРеестр: with specific test context and state.
	 *		.text : распечатать реестр
	 * 		.class : .Checkbutton
	 * 		.name : распечатать реестр
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject PrintcheckBox(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PrintcheckBox"), anchor, flags);
	}
	
	/**
	 * Далее: with default state.
	 *		.text : Далее >>
	 * 		.class : .Pushbutton
	 * 		.name : Далее >>
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ProvodNextbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ProvodNextbutton"));
	}
	/**
	 * Далее: with specific test context and state.
	 *		.text : Далее >>
	 * 		.class : .Pushbutton
	 * 		.name : Далее >>
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ProvodNextbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ProvodNextbutton"), anchor, flags);
	}
	
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with default state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002ПУБАНКАРОССИИЗАПАДНОЕ: with specific test context and state.
	 *		.text : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : 044582002 ПУ БАНКА РОССИИ ЗАПАДНОЕ
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	/**
	 * Text: with default state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject texttext() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("texttext"));
	}
	/**
	 * Text: with specific test context and state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject texttext(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("texttext"), anchor, flags);
	}
	
	

	protected VvodHelper()
	{
		setScriptName("PrProvod.PervVvod.Vvod");
	}
	
}

