// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ElObmen.EoIn;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EoInContr</b><br>
 * Generated     : <b>2013/04/11 17:22:22</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  àïğåëÿ 11, 2013
 * @author Admin
 */
public abstract class EoInContrHelper extends RationalTestScript
{
	/**
	 * Îòêëş÷èòüÏàíåëü: with default state.
	 *		.text : Îòêëş÷èòü ïàíåëü
	 * 		.class : TdxBarControl
	 * 		.name : Îòêëş÷èòü ïàíåëü
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanel() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanel"));
	}
	/**
	 * Îòêëş÷èòüÏàíåëü: with specific test context and state.
	 *		.text : Îòêëş÷èòü ïàíåëü
	 * 		.class : TdxBarControl
	 * 		.name : Îòêëş÷èòü ïàíåëü
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanel(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanel"), anchor, flags);
	}
	
	/**
	 * _044582002ÏÓÁÀÍÊÀĞÎÑÑÈÈÇÀÏÀÄÍÎÅ: with default state.
	 *		.text : _044582002ÏÓ ÁÀÍÊÀ ĞÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : _044582002ÏÓ ÁÀÍÊÀ ĞÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 */
	protected TopLevelSubitemTestObject SABSwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"));
	}
	/**
	 * _044582002ÏÓÁÀÍÊÀĞÎÑÑÈÈÇÀÏÀÄÍÎÅ: with specific test context and state.
	 *		.text : _044582002ÏÓ ÁÀÍÊÀ ĞÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 * 		.class : TpursMainForm
	 * 		.processName : purs_loader.exe
	 * 		.name : _044582002ÏÓ ÁÀÍÊÀ ĞÎÑÑÈÈ ÇÀÏÀÄÍÎÅ
	 */
	protected TopLevelSubitemTestObject SABSwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("SABSwindow"), anchor, flags);
	}
	
	/**
	 * TdxBarSubMenuControl: with default state.
	 *		.text : null
	 * 		.class : TdxBarSubMenuControl
	 * 		.processName : purs_loader.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject WorkWithFddMenu() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("WorkWithFddMenu"));
	}
	/**
	 * TdxBarSubMenuControl: with specific test context and state.
	 *		.text : null
	 * 		.class : TdxBarSubMenuControl
	 * 		.processName : purs_loader.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject WorkWithFddMenu(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("WorkWithFddMenu"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"), anchor, flags);
	}
	
	/**
	 * Äà: with default state.
	 *		.text : Äà
	 * 		.class : .Pushbutton
	 * 		.name : Äà
	 * 		.classIndex : 0
	 */
	protected GuiTestObject äàbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("äàbutton"));
	}
	/**
	 * Äà: with specific test context and state.
	 *		.text : Äà
	 * 		.class : .Pushbutton
	 * 		.name : Äà
	 * 		.classIndex : 0
	 */
	protected GuiTestObject äàbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("äàbutton"), anchor, flags);
	}
	
	/**
	 * ÎÊ: with default state.
	 *		.text : ÎÊ
	 * 		.class : .Pushbutton
	 * 		.name : ÎÊ
	 * 		.classIndex : 0
	 */
	protected GuiTestObject îêbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("îêbutton"));
	}
	/**
	 * ÎÊ: with specific test context and state.
	 *		.text : ÎÊ
	 * 		.class : .Pushbutton
	 * 		.name : ÎÊ
	 * 		.classIndex : 0
	 */
	protected GuiTestObject îêbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("îêbutton"), anchor, flags);
	}
	
	

	protected EoInContrHelper()
	{
		setScriptName("ElObmen.EoIn.EoInContr");
	}
	
}

