// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ElObmen.EoVer;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EoVerOotvet</b><br>
 * Generated     : <b>2013/04/18 20:15:10</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  апрел€ 18, 2013
 * @author Admin
 */
public abstract class EoVerOotvetHelper extends RationalTestScript
{
	/**
	 * ќтключитьѕанель: with default state.
	 *		.text : ќтключить панель
	 * 		.class : TdxBarControl
	 * 		.name : ќтключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanelErr() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanelErr"));
	}
	/**
	 * ќтключитьѕанель: with specific test context and state.
	 *		.text : ќтключить панель
	 * 		.class : TdxBarControl
	 * 		.name : ќтключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanelErr(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanelErr"), anchor, flags);
	}
	
	/**
	 * ќтключитьѕанель: with default state.
	 *		.text : ќтключить панель
	 * 		.class : TdxBarControl
	 * 		.name : ќтключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanelObr() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanelObr"));
	}
	/**
	 * ќтключитьѕанель: with specific test context and state.
	 *		.text : ќтключить панель
	 * 		.class : TdxBarControl
	 * 		.name : ќтключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject IconPanelObr(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("IconPanelObr"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMemuTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMemuTree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMemuTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMemuTree"), anchor, flags);
	}
	
	/**
	 * TcxTreeList: with default state.
	 *		.text : null
	 * 		.class : TcxTreeList
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tcxTreeListwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tcxTreeListwindow"));
	}
	/**
	 * TcxTreeList: with specific test context and state.
	 *		.text : null
	 * 		.class : TcxTreeList
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tcxTreeListwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tcxTreeListwindow"), anchor, flags);
	}
	
	/**
	 * «ачислить лиенту: with default state.
	 *		.text : «ачислить клиенту
	 * 		.class : .Pushbutton
	 * 		.name : «ачислить клиенту
	 * 		.classIndex : 0
	 */
	protected GuiTestObject зачислить лиентуbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("зачислить лиентуbutton"));
	}
	/**
	 * «ачислить лиенту: with specific test context and state.
	 *		.text : «ачислить клиенту
	 * 		.class : .Pushbutton
	 * 		.name : «ачислить клиенту
	 * 		.classIndex : 0
	 */
	protected GuiTestObject зачислить лиентуbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("зачислить лиентуbutton"), anchor, flags);
	}
	
	

	protected EoVerOotvetHelper()
	{
		setScriptName("ElObmen.EoVer.EoVerOotvet");
	}
	
}

