// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ElObmen.EoVer;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EoVerOcontr</b><br>
 * Generated     : <b>2013/04/12 15:36:19</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  апреля 12, 2013
 * @author Admin
 */
public abstract class EoVerOcontrHelper extends RationalTestScript
{
	/**
	 * ОтключитьПанель: with default state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject iconPanel() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("iconPanel"));
	}
	/**
	 * ОтключитьПанель: with specific test context and state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject iconPanel(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("iconPanel"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"), anchor, flags);
	}
	
	

	protected EoVerOcontrHelper()
	{
		setScriptName("ElObmen.EoVer.EoVerOcontr");
	}
	
}

