// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ElObmen.EoVer;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EoVerNotvet</b><br>
 * Generated     : <b>2013/04/11 17:17:12</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  апреля 11, 2013
 * @author Admin
 */
public abstract class EoVerNotvetHelper extends RationalTestScript
{
	/**
	 * Ошибка: with default state.
	 *		.text : Ошибка
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Ошибка
	 */
	protected TopLevelSubitemTestObject ErrorWindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ErrorWindow"));
	}
	/**
	 * Ошибка: with specific test context and state.
	 *		.text : Ошибка
	 * 		.class : #32770
	 * 		.processName : purs_loader.exe
	 * 		.name : Ошибка
	 */
	protected TopLevelSubitemTestObject ErrorWindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ErrorWindow"), anchor, flags);
	}
	
	/**
	 * ОтключитьПанель: with default state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject FormEsWinIcon() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("FormEsWinIcon"));
	}
	/**
	 * ОтключитьПанель: with specific test context and state.
	 *		.text : Отключить панель
	 * 		.class : TdxBarControl
	 * 		.name : Отключить панель
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject FormEsWinIcon(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("FormEsWinIcon"), anchor, flags);
	}
	
	/**
	 * ОК: with default state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OKbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("OKbutton"));
	}
	/**
	 * ОК: with specific test context and state.
	 *		.text : ОК
	 * 		.class : .Pushbutton
	 * 		.name : ОК
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OKbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("OKbutton"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject mainMenuTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("mainMenuTree"), anchor, flags);
	}
	
	

	protected EoVerNotvetHelper()
	{
		setScriptName("ElObmen.EoVer.EoVerNotvet");
	}
	
}

